auth_var: GITHUB_TOKEN
repo: correlation-one/c1
profiles:
  - name: 'by category'
    bins:
      - filter: "^category: enhancement"
        main_label: "category: enhancement"
        name: "Enhancement"

      - filter: "^category: bug"
        main_label: "category: bug"
        name: "Bug"

      - filter: "^category: meta"
        main_label: "category: meta"
        name: "Meta"

      - filter: "^category: question"
        main_label: "category: question"
        name: "Question"

  - name: 'by status'
    bins:
      - filter: '^status: help-wanted'
        main_label: 'status: help-wanted'
        name: 'Help Wanted'

      - filter: '^status: work-in-progress'
        main_label: 'status: work-in-progress'
        name: 'In Progress'

      - filter: '^status: blocked'
        main_label: 'status: blocked'
        name: 'Blocked'

      - filter: '^status: ready-for-review'
        main_label: 'status: ready-for-review'
        name: 'Ready for Review'


  - name: 'by priority'
    bins:
      - filter: '^priority: high'
        main_label: 'priority: high'
        name: 'High Priority'

      - filter: '^priority: low'
        main_label: 'priority: low'
        name: 'Low Priority'

  - name: 'by topic'
    bins:
      - filter: '^topic: documentation'
        main_label: 'topic: documentation'
        name: 'Documentation'

      - filter: '^topic: frontend'
        main_label: 'topic: frontend'
        name: 'Frontend'

      - filter: '^topic: ops'
        main_label: 'topic: ops'
        name: 'Ops'

      - filter: '^topic: testing'
        main_label: 'topic: testing'
        name: 'Testing'