auth_var: GITHUB_TOKEN
repo: correlation-one/c1
bins:
  - filter: "^Category: Enhancement"
    name: aaa
  - filter: "^Type: SDLKfjhsdlkfh"
    name: bbb
    order:
      - "A"
      - "B"
      - "C"
  - filter: "^.*$"
    name: whatevs